### PR TITLE
Read data. Make some tests.

### PR DESCRIPTION
**Pull request by Oriundi**

### CODE REVIEW

**Comment by epogrebnyak** [comment]
Not clear, which part is the import test with hardcoded constants?

**Comment by Oriundi** [comment]
Lines 302-315. But after some input data manipulations. I'm making a function to test the file parsing without any data changing.

**Comment by epogrebnyak** [comment]
Which file?

сб, 2 янв. 2016, 2:40, Oriundi notifications@github.com:

**Comment by Oriundi** [comment]
sorry. pseudo.py

**Comment by epogrebnyak** [comment]
Much more convinient to provide a clickable link... Will look now.
2 янв. 2016 г. 2:44 пользователь "Oriundi" notifications@github.com
написал:

**Comment by epogrebnyak** [comment]
Sorry, but these are not tests on a sense I was describing them, not
accepted as import test.

Please review import test in test_mwe.py.

сб, 2 янв. 2016, 2:46, Evgeny Pogrebnyak e.pogrebnyak@gmail.com:

**Comment by Oriundi** [comment]
working on it. I see.

**Comment by Oriundi** [comment]
https://github.com/Oriundi/rosstat-806-regional/blob/master/pseudo.py
lines from 322. I test if all regions names from actual_sidebar_list are in file read. Also possible to test years or month in the file, also check the data if they are float. But all this is regarding the file with all rows read. Is it something like you want?

**Pull request closed without merging**
